import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';
import { Appearance } from 'react-native';

export const themes = {
    light: {
        backgroundColor: '#F5F5F5',
        textColor: '#1E1E1E',
        accentColor: '#007AFF',
        tabBarColor: '#ffffff',
        tabBarInactiveTintColor: 'gray',
        tabBarBorderColor: '#e0e0e0',
        headerBackground: '#ffffff',
        headerText: '#1E1E1E',
        coinContainerBg: 'rgba(0, 0, 0, 0.05)',
        coinText: '#1E1E1E',
        statusCardBg: '#E0E0E0',
        statusCardBorder: 'rgba(0,0,0,0.1)',
        statusCardGradient: ['#E0E0E0', '#E0E0E0'],
        statusText: '#4A4A4A',
        fabBg: '#007AFF',
        unselectedTopBg: '#E0E0E0',
        unselectedBottomBg: '#C0C0C0',
        selectedTopBg: '#c9395a',
        selectedBottomBg: '#7e2237',
        selectedText: '#FFFFFF',
        unselectedDayNameText: '#666666',
        unselectedDayNumberText: '#1E1E1E',
        dividerShadowColor: 'rgba(0, 0, 0, 0.2)',
        timeBlockCardBg: '#FFFFFF',
        cardBorderColor: 'rgba(0,0,0,0.1)',
        timeBlockIcon: '#666666',
        timeBlockTitleText: '#1E1E1E',
        sessionItemBg: 'rgba(0, 0, 0, 0.05)',
        sessionItemBorder: 'rgba(0,0,0,0.1)',
        sessionItemCompletedBg: 'rgba(0, 122, 255, 0.1)',
        sessionItemCompletedBorder: 'rgba(0, 122, 255, 0.2)',
        sessionTimeText: '#888888',
        sessionTimeTextCompleted: '#888888',
        sessionText: '#1E1E1E',
        sessionTextCompleted: '#888888',
        taskIconContainerBg: 'rgba(0, 0, 0, 0.05)',
        taskIconContainerBorder: 'rgba(0, 0, 0, 0.1)',
        checkboxBorder: '#888888',
        checkboxCheckedBg: '#007AFF',
        checkboxCheckedBorder: '#007AFF',
        checkboxCheckmark: '#FFFFFF',
        deleteIconColor: '#FF3B30',
        editIconColor: '#FF9500',
        modalBg: '#FFFFFF',
        modalTitleText: '#1E1E1E',
        modalText: '#4A4A4A',
        modalBorder: 'rgba(0,0,0,0.1)',
        inputLabelText: '#888888',
        inputBg: 'rgba(0, 0, 0, 0.05)',
        inputIcon: '#888888',
        inputPlaceholder: '#888888',
        inputText: '#1E1E1E',
        modalDayButtonBg: '#E0E0E0',
        selectedDayText: '#FFFFFF',
        dayText: '#1E1E1E',
        disabledBtnBg: 'rgba(0, 0, 0, 0.1)',
        modalMainActionBtnText: '#FFFFFF',
        dividerLine: '#E0E0E0',
        dividerText: '#888888',
        settingRowBg: '#E0E0E0',
        iconColor: '#666666',
        switchTrackOn: '#34C759',
        switchTrackOff: '#C0C0C0',
        switchThumbOff: '#F5F5F5',
        testButtonBg: '#C0C0C0',
        noSessionsText: '#4A4A4A',
        noSessionsSubText: '#666666',
        focusBackground: '#F5F5F5',
        focusHeading: '#1E1E1E',
        focusSwitcherBg: '#E0E0E0',
        focusSwitcherText: '#666666',
        focusSwitcherActiveBg: '#C0C0C0',
        focusSwitcherActiveText: '#1E1E1E',
        focusTimeDisplay: '#007AFF',
        focusInputBg: '#E0E0E0',
        focusInputText: '#1E1E1E',
        focusInputPlaceholder: '#888888',
        focusInputLabel: '#666666',
        focusButtonText: '#FFFFFF',
        focusResetBg: '#C0C0C0',
        focusResetIcon: '#1E1E1E',
        focusCardBg: '#E0E0E0',
        focusCardText: '#1E1E1E',
        focusCardValueText: '#666666',
        focusTipText: '#888888',
        focusStartButtonGradient: ['#4188ff', '#345cef'],
        noteColors: ["#FFFFFF", "#F0F0F0", "#E0E0E0", "#D0D0D0", "#C0C0C0"],
        notesBackground: '#F5F5F5',
        notesHeader: '#1E1E1E',
        notesSearchBg: '#E0E0E0',
        notesSearchText: '#1E1E1E',
        notesSearchIcon: '#666666',
        notesPlaceholder: '#888888',
        notesGridColumnBg: '#F5F5F5',
        notesCardSelectedBorder: '#007AFF',
        notesFabBg: '#007AFF',
        notesFabIcon: '#FFFFFF',
        notesFabLabelBg: 'rgba(0,0,0,0.7)',
        notesFabLabelText: '#FFFFFF',
        notesModalBg: '#FFFFFF',
        notesModalText: '#1E1E1E',
        notesModalInputTitleBg: 'rgba(0,0,0,0.05)',
        notesModalInputContent: '#4A4A4A',
        notesModalInputTitle: '#1E1E1E',
        notesModalInputPlaceholder: '#888888',
        notesChecklistItemText: '#1E1E1E',
        notesChecklistItemCompleted: '#888888',
        notesAddChecklistItemText: '#007AFF',
        notesFooterBg: '#E0E0E0',
        notesFooterIcon: '#888888',
        notesFooterIconActive: '#007AFF',
        notesEmptyText: '#888888',
        notesMoreItemsText: '#666666',
        notesSelectionOverlay: 'rgba(0, 122, 255, 0.2)',
        notesSortDropdownBg: '#E0E0E0',
        notesSortDropdownText: '#4A4A4A',
        notesSortDropdownActiveText: '#007AFF',
        notesSortDropdownBorder: '#C0C0C0',
        notesBadgeBg: 'rgba(255,255,255,0.7)',
        notesLockedOverlayBg: 'rgba(0,0,0,0.3)',
        notesModalButtonBg: '#E0E0E0',
        notesModalButtonIcon: '#888888',
        notesModalInput: '#1E1E1E',
        notesColorOptionSelected: '#FFFFFF',
    },
    dark: {
        backgroundColor: '#121212',
        textColor: '#E5E5E5',
        accentColor: '#007AFF',
        tabBarColor: '#1E1E1E',
        tabBarInactiveTintColor: 'gray',
        tabBarBorderColor: '#222',
        headerBackground: '#1E1E1E',
        headerText: '#E5E5E5',
        coinContainerBg: 'rgba(255, 255, 255, 0.1)',
        coinText: '#FFFFFF',
        statusCardBg: '#2A2A3A',
        statusCardBorder: 'rgba(89, 80, 137, 0.45)',
        statusCardGradient: ['#2A2A3A', '#1A1A2A'],
        statusText: '#E0E0E0',
        fabBg: '#007AFF',
        unselectedTopBg: '#1c1c1e',
        unselectedBottomBg: '#2c2c2e',
        selectedTopBg: '#c9395a',
        selectedBottomBg: '#7e2237',
        selectedText: '#FFFFFF',
        unselectedDayNameText: '#AEAEB2',
        unselectedDayNumberText: '#FFFFFF',
        dividerShadowColor: 'rgba(50, 48, 48, 0.3)',
        timeBlockCardBg: '#2a2a3a',
        cardBorderColor: 'rgba(89, 80, 137, 0.45)',
        timeBlockIcon: '#E5E5E5',
        timeBlockTitleText: '#FFFFFF',
        sessionItemBg: 'rgba(255, 255, 255, 0.05)',
        sessionItemBorder: 'rgba(255, 255, 255, 0.1)',
        sessionItemCompletedBg: 'rgba(0, 122, 255, 0.2)',
        sessionItemCompletedBorder: 'rgba(0, 122, 255, 0.3)',
        sessionTimeText: '#AEAEB2',
        sessionTimeTextCompleted: '#8E8E93',
        sessionText: '#FFFFFF',
        sessionTextCompleted: '#8E8E93',
        taskIconContainerBg: 'rgba(255, 255, 255, 0.05)',
        taskIconContainerBorder: 'rgba(255, 255, 255, 0.1)',
        checkboxBorder: '#4A4466',
        checkboxCheckedBg: '#007AFF',
        checkboxCheckedBorder: '#007AFF',
        checkboxCheckmark: '#FFFFFF',
        deleteIconColor: '#FF3B30',
        editIconColor: '#FF9500',
        modalBg: '#1C1C1E',
        modalTitleText: '#fff',
        modalText: '#E5E5EA',
        modalBorder: 'rgba(255,255,255,0.1)',
        inputLabelText: '#8A8A8E',
        inputBg: '#31313643',
        inputIcon: '#888',
        inputPlaceholder: '#888',
        inputText: '#fff',
        modalDayButtonBg: '#3A3A3C',
        selectedDayText: '#fff',
        dayText: '#fff',
        disabledBtnBg: '#31313643',
        modalMainActionBtnText: '#fff',
        dividerLine: '#3A3A3C',
        dividerText: '#8A8A8E',
        settingRowBg: 'rgba(44, 44, 46, 0.7)',
        iconColor: '#8A8A8E',
        switchTrackOn: '#81b0ff',
        switchTrackOff: '#767577',
        switchThumbOff: '#f4f3f4',
        testButtonBg: '#1C1C1E',
        noSessionsText: '#A0A0A0',
        noSessionsSubText: '#777',
        focusBackground: '#121212',
        focusHeading: '#E5E5E5',
        focusSwitcherBg: '#1E1E1E',
        focusSwitcherText: '#666666',
        focusSwitcherActiveBg: '#333942',
        focusSwitcherActiveText: '#FFFFFF',
        focusTimeDisplay: '#7ceffd',
        focusInputBg: '#1E1E1E',
        focusInputText: '#FFFFFF',
        focusInputPlaceholder: '#888888',
        focusInputLabel: '#888888',
        focusButtonText: '#FFFFFF',
        focusResetBg: '#1E1E1E',
        focusResetIcon: '#FFFFFF',
        focusCardBg: '#1E1E1E',
        focusCardText: '#FFFFFF',
        focusCardValueText: '#A0A0A0',
        focusTipText: '#666666',
        focusStartButtonGradient: ['#1E1E1E', '#1E1E1E'],
        noteColors: ["#282A36", "#44475A", "#6272A4", "#504F6D", "#21222C", "#3B3A54"],
        notesBackground: '#121212',
        notesHeader: '#E5E5E5',
        notesSearchBg: '#1E1E1E',
        notesSearchText: '#E5E5E5',
        notesSearchIcon: '#AEAEB2',
        notesPlaceholder: '#8A8A8E',
        notesGridColumnBg: '#121212',
        notesCardSelectedBorder: '#007AFF',
        notesFabBg: '#007AFF',
        notesFabIcon: '#FFFFFF',
        notesFabLabelBg: 'rgba(0,0,0,0.7)',
        notesFabLabelText: '#FFFFFF',
        notesModalBg: '#1C1C1E',
        notesModalText: '#E5E5E5',
        notesModalInputTitleBg: 'rgba(255,255,255,0.05)',
        notesModalInputContent: '#AEAEB2',
        notesModalInputTitle: '#E5E5E5',
        notesModalInputPlaceholder: '#999',
        notesChecklistItemText: '#E5E5E5',
        notesChecklistItemCompleted: '#666',
        notesAddChecklistItemText: '#007AFF',
        notesFooterBg: '#1E1E1E',
        notesFooterIcon: '#AEAEB2',
        notesFooterIconActive: '#007AFF',
        notesEmptyText: '#888888',
        notesMoreItemsText: '#bd93f9',
        notesSelectionOverlay: 'rgba(0, 122, 255, 0.2)',
        notesSortDropdownBg: '#2C2C2E',
        notesSortDropdownText: '#E5E5EA',
        notesSortDropdownActiveText: '#007AFF',
        notesSortDropdownBorder: '#3A3A3C',
        notesBadgeBg: 'rgba(255,255,255,0.7)',
        notesLockedOverlayBg: 'rgba(0,0,0,0.3)',
        notesModalButtonBg: '#1E1E1E',
        notesModalButtonIcon: '#AEAEB2',
        notesModalInput: '#E5E5E5',
        notesColorOptionSelected: '#FFFFFF',
    },
    classic: {
        backgroundColor: '#0e091fff',
        textColor: '#E5E5E5',
        accentColor: '#007AFF',
        tabBarColor: '#0b111d',
        tabBarInactiveTintColor: 'gray',
        tabBarBorderColor: '#222',
        headerBackground: '#0b111d',
        headerText: '#FFFFFF',
        coinContainerBg: 'rgba(255, 255, 255, 0.1)',
        coinText: '#FFFFFF',
        statusCardBg: '#2A2A3A',
        statusCardBorder: 'rgba(89, 80, 137, 0.45)',
        statusCardGradient: ['#2A2A3A', '#1A1A2A'],
        statusText: '#E0E0E0',
        fabBg: '#007AFF',
        unselectedTopBg: '#1c1c1e',
        unselectedBottomBg: '#2c2c2e',
        selectedTopBg: '#c9395a',
        selectedBottomBg: '#7e2237',
        selectedText: '#FFFFFF',
        unselectedDayNameText: '#AEAEB2',
        unselectedDayNumberText: '#FFFFFF',
        dividerShadowColor: 'rgba(50, 48, 48, 0.3)',
        timeBlockCardBg: 'transparent',
        cardBorderColor: 'rgba(89, 80, 137, 0.45)',
        timeBlockIcon: '#FFFFFF',
        timeBlockTitleText: '#FFFFFF',
        sessionItemBg: 'rgba(0, 0, 0, 0.18)',
        sessionItemBorder: 'rgba(113, 113, 113, 0.04)',
        sessionItemCompletedBg: 'rgba(0, 122, 255, 0.2)',
        sessionItemCompletedBorder: 'rgba(0, 122, 255, 0.3)',
        sessionTimeText: '#AEAEB2',
        sessionTimeTextCompleted: '#8E8E93',
        sessionText: '#FFFFFF',
        sessionTextCompleted: '#8E8E93',
        taskIconContainerBg: '#272b3e70',
        taskIconContainerBorder: 'rgba(113, 113, 113, 0.1)',
        checkboxBorder: '#4A4466',
        checkboxCheckedBg: '#007AFF',
        checkboxCheckedBorder: '#007AFF',
        checkboxCheckmark: '#FFFFFF',
        deleteIconColor: '#FF3B30',
        editIconColor: '#FF9500',
        modalBg: '#1C1C1E',
        modalTitleText: '#fff',
        modalText: '#E5E5EA',
        modalBorder: 'rgba(255,255,255,0.1)',
        inputLabelText: '#8A8A8E',
        inputBg: '#31313643',
        inputIcon: '#888',
        inputPlaceholder: '#888',
        inputText: '#fff',
        modalDayButtonBg: '#3A3A3C',
        selectedDayText: '#fff',
        dayText: '#fff',
        disabledBtnBg: '#31313643',
        modalMainActionBtnText: '#fff',
        dividerLine: '#3A3A3C',
        dividerText: '#8A8A8E',
        settingRowBg: 'rgba(44, 44, 46, 0.7)',
        iconColor: '#8A8A8E',
        switchTrackOn: '#81b0ff',
        switchTrackOff: '#767577',
        switchThumbOff: '#f4f3f4',
        testButtonBg: '#1C1C1E',
        noSessionsText: '#A0A0A0',
        noSessionsSubText: '#777',
        focusBackground: '#0e091fff',
        focusHeading: '#E5E5E5',
        focusSwitcherBg: '#18202e',
        focusSwitcherText: '#9e9e9e86',
        focusSwitcherActiveBg: '#3339426c',
        focusSwitcherActiveText: '#FFFFFF',
        focusTimeDisplay: '#7ceffd',
        focusInputBg: '#18202e',
        focusInputText: '#FFFFFF',
        focusInputPlaceholder: '#888888',
        focusInputLabel: '#888888',
        focusButtonText: '#FFFFFF',
        focusResetBg: '#18202e',
        focusResetIcon: '#FFFFFF',
        focusCardBg: '#18202e',
        focusCardText: '#FFFFFF',
        focusCardValueText: '#A0A0A0',
        focusTipText: '#666',
        focusStartButtonGradient: ['#007AFF', '#0047b3'],
        noteColors: ["#282A36", "#44475A", "#6272A4", "#504F6D", "#21222C", "#3B3A54"],
        notesBackground: '#0b111d',
        notesHeader: '#E5E5E5',
        notesSearchBg: '#1C1C1E',
        notesSearchText: '#E5E5E5',
        notesSearchIcon: '#8A8A8E',
        notesPlaceholder: '#8A8A8E',
        notesGridColumnBg: '#0b111d',
        notesCardSelectedBorder: '#007AFF',
        notesFabBg: '#007AFF',
        notesFabIcon: '#FFFFFF',
        notesFabLabelBg: 'rgba(0,0,0,0.7)',
        notesFabLabelText: '#FFFFFF',
        notesModalBg: '#080d15ff',
        notesModalText: '#E5E5E5',
        notesModalInputTitleBg: 'transparent',
        notesModalInputContent: '#ddd',
        notesModalInputTitle: '#fff',
        notesModalInputPlaceholder: '#999',
        notesChecklistItemText: '#fff',
        notesChecklistItemCompleted: '#666',
        notesAddChecklistItemText: '#007AFF',
        notesFooterBg: '#1C1C1E',
        notesFooterIcon: '#AEAEB2',
        notesFooterIconActive: '#007AFF',
        notesEmptyText: '#888',
        notesMoreItemsText: '#bd93f9',
        notesSelectionOverlay: 'rgba(0, 122, 255, 0.2)',
        notesSortDropdownBg: '#2C2C2E',
        notesSortDropdownText: '#E5E5EA',
        notesSortDropdownActiveText: '#007AFF',
        notesSortDropdownBorder: '#3A3A3C',
        notesBadgeBg: 'rgba(255,255,255,0.7)',
        notesLockedOverlayBg: 'rgba(0,0,0,0.3)',
        notesModalButtonBg: '#333',
        notesModalButtonIcon: '#AEAEB2',
        notesModalInput: '#fff',
        notesColorOptionSelected: '#fff',
        timeBlockCardGradients: {
            Morning: {
                base: ['#181b27', '#181b27'],
                topLeft: '#ba4f25ff',
                topRight: '#2f2a67ff',
                icon: '#f1932b',
            },
            Midday: {
                base: ['#171a26', '#171a26'],
                topLeft: '#2f2470ff',
                topRight: '#1a1f31',
                icon: '#1e61ef',
            },
            Evening: {
                base: ['#171a26', '#171a26'],
                topLeft: '#3b0642ff',
                topRight: '#452737ff',
                icon: '#FD5E53',
            },
            Night: {
                base: ['#171a26', '#171a26'],
                topLeft: '#272465ff',
                topRight: '#5f4e92ff',
                icon: '#D8D8FF',
            },
        },
    },
};

export type ThemeName = keyof typeof themes;
export type Theme = typeof themes['light'];

type ThemeContextType = {
    themeName: ThemeName;
    colors: Theme;
    setThemeName: (name: ThemeName) => void;
};

const ThemeContext = createContext<ThemeContextType>({
    themeName: 'classic',
    colors: themes.classic,
    setThemeName: () => {},
});

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [themeName, setThemeName] = useState<ThemeName>('classic');

    useEffect(() => {
        const loadTheme = async () => {
            const storedTheme = await AsyncStorage.getItem("userTheme");
            const systemTheme = Appearance.getColorScheme() || 'classic';
            setThemeName((storedTheme || systemTheme) as ThemeName);
        };

        loadTheme();

        const subscription = Appearance.addChangeListener(({ colorScheme }) => {
            setThemeName((colorScheme || 'classic') as ThemeName);
        });

        return () => subscription.remove();
    }, []);

    const colors = themes[themeName];

    return (
        <ThemeContext.Provider value={{ themeName, colors, setThemeName }}>
            {children}
        </ThemeContext.Provider>
    );
};

export const useTheme = () => useContext(ThemeContext);
