export const routineTemplates = [
  {
    id: "1",
    name: "Study Plan (Full Day)",
    sessions: [
      {
        id: "s1",
        title: "Wake Up & Freshen Up",
        start: "6:30 AM",
        end: "7:00 AM",
      },
      { id: "s2", title: "Light Exercise", start: "7:00 AM", end: "7:30 AM" },
      { id: "s3", title: "Breakfast", start: "7:30 AM", end: "8:00 AM" },
      { id: "s4", title: "Math Study", start: "8:00 AM", end: "9:30 AM" },
      { id: "s5", title: "Break", start: "9:30 AM", end: "9:45 AM" },
      { id: "s6", title: "Science Study", start: "9:45 AM", end: "11:15 AM" },
      { id: "s7", title: "Revision", start: "11:15 AM", end: "12:00 PM" },
      { id: "s8", title: "Lunch & Rest", start: "12:00 PM", end: "1:30 PM" },
      { id: "s9", title: "Literature Study", start: "1:30 PM", end: "3:00 PM" },
      { id: "s10", title: "Short Break", start: "3:00 PM", end: "3:15 PM" },
      {
        id: "s11",
        title: "Mock Test Practice",
        start: "3:15 PM",
        end: "4:30 PM",
      },
      { id: "s12", title: "Evening Walk", start: "5:00 PM", end: "5:30 PM" },
      { id: "s13", title: "Dinner", start: "7:30 PM", end: "8:00 PM" },
      {
        id: "s14",
        title: "Light Reading / Hobby",
        start: "8:00 PM",
        end: "9:00 PM",
      },
      { id: "s15", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "2",
    name: "Morning Routine (Balanced)",
    sessions: [
      { id: "s16", title: "Wake Up", start: "5:30 AM", end: "6:00 AM" },
      {
        id: "s17",
        title: "Stretching or Yoga",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      {
        id: "s18",
        title: "Reading or Journaling",
        start: "6:30 AM",
        end: "7:00 AM",
      },
      {
        id: "s19",
        title: "Breakfast & Planning",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      {
        id: "s20",
        title: "Work / Study Block 1",
        start: "7:30 AM",
        end: "9:30 AM",
      },
      { id: "s21", title: "Short Break", start: "9:30 AM", end: "9:45 AM" },
      {
        id: "s22",
        title: "Work / Study Block 2",
        start: "9:45 AM",
        end: "11:45 AM",
      },
      { id: "s23", title: "Lunch", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s24",
        title: "Relaxation / Nap",
        start: "1:00 PM",
        end: "1:30 PM",
      },
      {
        id: "s25",
        title: "Work / Study Block 3",
        start: "1:30 PM",
        end: "4:00 PM",
      },
      { id: "s26", title: "Exercise / Walk", start: "4:00 PM", end: "4:30 PM" },
      { id: "s27", title: "Dinner", start: "7:00 PM", end: "7:30 PM" },
      { id: "s28", title: "Relax & Leisure", start: "7:30 PM", end: "9:00 PM" },
      { id: "s29", title: "Prepare for Bed", start: "9:00 PM", end: "9:30 PM" },
      { id: "s30", title: "Sleep", start: "10:00 PM", end: "5:30 AM" },
    ],
  },
  {
    id: "3",
    name: "Developer Daily Schedule (Full Day)",
    sessions: [
      {
        id: "s31",
        title: "Wake Up & Morning Routine",
        start: "7:00 AM",
        end: "8:00 AM",
      },
      {
        id: "s32",
        title: "Code Review & Fixes",
        start: "9:00 AM",
        end: "10:30 AM",
      },
      {
        id: "s33",
        title: "Stand-up Meeting",
        start: "10:30 AM",
        end: "11:00 AM",
      },
      {
        id: "s34",
        title: "Feature Development",
        start: "11:00 AM",
        end: "1:00 PM",
      },
      { id: "s35", title: "Lunch Break", start: "1:00 PM", end: "2:00 PM" },
      {
        id: "s36",
        title: "Deep Work (Coding/Design)",
        start: "2:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s37",
        title: "Testing & Debugging",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      {
        id: "s38",
        title: "Wrap-up & Commit Code",
        start: "5:00 PM",
        end: "5:30 PM",
      },
      {
        id: "s39",
        title: "Evening Learning (Blog/Videos)",
        start: "6:30 PM",
        end: "7:30 PM",
      },
      { id: "s40", title: "Dinner & Rest", start: "8:00 PM", end: "9:00 PM" },
      { id: "s41", title: "Sleep", start: "10:30 PM", end: "7:00 AM" },
    ],
  },
  {
    id: "4",
    name: "Freelancer Routine",
    sessions: [
      {
        id: "s42",
        title: "Wake Up & Breakfast",
        start: "8:00 AM",
        end: "8:30 AM",
      },
      {
        id: "s43",
        title: "Client Communication",
        start: "9:00 AM",
        end: "10:00 AM",
      },
      { id: "s44", title: "Project Work", start: "10:00 AM", end: "1:00 PM" },
      { id: "s45", title: "Lunch Break", start: "1:00 PM", end: "2:00 PM" },
      {
        id: "s46",
        title: "New Client Outreach",
        start: "2:00 PM",
        end: "3:00 PM",
      },
      { id: "s47", title: "Continue Work", start: "3:00 PM", end: "5:00 PM" },
      {
        id: "s48",
        title: "Learning & Upskilling",
        start: "6:00 PM",
        end: "7:30 PM",
      },
      { id: "s49", title: "Dinner & Relax", start: "8:00 PM", end: "9:00 PM" },
      { id: "s50", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "5",
    name: "Content Creator Day",
    sessions: [
      {
        id: "s51",
        title: "Wake Up & Planning",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      { id: "s52", title: "Idea Planning", start: "7:30 AM", end: "8:30 AM" },
      { id: "s53", title: "Script Writing", start: "8:30 AM", end: "9:30 AM" },
      { id: "s54", title: "Recording", start: "9:30 AM", end: "12:00 PM" },
      { id: "s55", title: "Lunch Break", start: "12:00 PM", end: "1:00 PM" },
      { id: "s56", title: "Editing", start: "1:00 PM", end: "3:00 PM" },
      { id: "s57", title: "Uploading & SEO", start: "3:00 PM", end: "4:00 PM" },
      {
        id: "s58",
        title: "Social Media Engagement",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      {
        id: "s59",
        title: "Relax & Plan Tomorrow",
        start: "5:00 PM",
        end: "6:00 PM",
      },
      { id: "s60", title: "Dinner & Rest", start: "7:00 PM", end: "8:00 PM" },
      { id: "s61", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "6",
    name: "Fitness Enthusiast Routine",
    sessions: [
      {
        id: "s62",
        title: "Wake Up & Hydrate",
        start: "5:30 AM",
        end: "6:00 AM",
      },
      { id: "s63", title: "Morning Cardio", start: "6:00 AM", end: "7:00 AM" },
      {
        id: "s64",
        title: "Breakfast & Prep",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      {
        id: "s65",
        title: "Strength Training",
        start: "8:00 AM",
        end: "9:30 AM",
      },
      { id: "s66", title: "Work / Study", start: "10:00 AM", end: "1:00 PM" },
      { id: "s67", title: "Lunch", start: "1:00 PM", end: "2:00 PM" },
      {
        id: "s68",
        title: "Stretch & Recovery",
        start: "2:00 PM",
        end: "3:00 PM",
      },
      {
        id: "s69",
        title: "Evening Walk / Yoga",
        start: "5:00 PM",
        end: "6:00 PM",
      },
      { id: "s70", title: "Dinner", start: "7:00 PM", end: "7:30 PM" },
      {
        id: "s71",
        title: "Relax & Sleep Prep",
        start: "8:00 PM",
        end: "9:00 PM",
      },
      { id: "s72", title: "Sleep", start: "10:00 PM", end: "5:30 AM" },
    ],
  },
  {
    id: "7",
    name: "Entrepreneur's Schedule",
    sessions: [
      {
        id: "s73",
        title: "Wake Up & Meditation",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      {
        id: "s74",
        title: "Plan Day & Emails",
        start: "6:30 AM",
        end: "7:30 AM",
      },
      { id: "s75", title: "Team Meeting", start: "8:00 AM", end: "9:00 AM" },
      {
        id: "s76",
        title: "Product Development",
        start: "9:00 AM",
        end: "12:00 PM",
      },
      {
        id: "s77",
        title: "Lunch & Networking",
        start: "12:00 PM",
        end: "1:00 PM",
      },
      { id: "s78", title: "Client Calls", start: "1:00 PM", end: "3:00 PM" },
      {
        id: "s79",
        title: "Marketing & Strategy",
        start: "3:00 PM",
        end: "4:30 PM",
      },
      {
        id: "s80",
        title: "Wrap-up & Review",
        start: "4:30 PM",
        end: "5:00 PM",
      },
      {
        id: "s81",
        title: "Dinner & Family Time",
        start: "6:30 PM",
        end: "8:00 PM",
      },
      { id: "s82", title: "Reading & Relax", start: "8:00 PM", end: "9:30 PM" },
      { id: "s83", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "8",
    name: "Teacher's Daily Routine",
    sessions: [
      {
        id: "s84",
        title: "Wake Up & Prepare",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      {
        id: "s85",
        title: "Breakfast & Review Lesson",
        start: "6:30 AM",
        end: "7:30 AM",
      },
      {
        id: "s86",
        title: "Classroom Teaching",
        start: "8:00 AM",
        end: "12:00 PM",
      },
      { id: "s87", title: "Lunch & Break", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s88",
        title: "Grading & Planning",
        start: "1:00 PM",
        end: "3:00 PM",
      },
      { id: "s89", title: "Parent Meetings", start: "3:00 PM", end: "4:00 PM" },
      {
        id: "s90",
        title: "Professional Development",
        start: "4:00 PM",
        end: "5:30 PM",
      },
      { id: "s91", title: "Dinner & Relax", start: "6:00 PM", end: "7:00 PM" },
      {
        id: "s92",
        title: "Reading & Sleep Prep",
        start: "7:00 PM",
        end: "9:00 PM",
      },
      { id: "s93", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "9",
    name: "Artist's Daily Routine",
    sessions: [
      {
        id: "s94",
        title: "Wake Up & Morning Walk",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      {
        id: "s95",
        title: "Sketching & Idea Generation",
        start: "7:30 AM",
        end: "9:30 AM",
      },
      { id: "s96", title: "Breakfast", start: "9:30 AM", end: "10:00 AM" },
      {
        id: "s97",
        title: "Painting / Work Session",
        start: "10:00 AM",
        end: "1:00 PM",
      },
      { id: "s98", title: "Lunch & Rest", start: "1:00 PM", end: "2:00 PM" },
      {
        id: "s99",
        title: "Creative Exploration",
        start: "2:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s100",
        title: "Gallery Visits / Networking",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      { id: "s101", title: "Dinner & Relax", start: "7:00 PM", end: "8:00 PM" },
      {
        id: "s102",
        title: "Reading / Inspiration",
        start: "8:00 PM",
        end: "9:30 PM",
      },
      { id: "s103", title: "Sleep", start: "10:00 PM", end: "7:00 AM" },
    ],
  },
  {
    id: "10",
    name: "Salesperson Routine",
    sessions: [
      {
        id: "s104",
        title: "Wake Up & Prepare",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      {
        id: "s105",
        title: "Cold Calls & Emails",
        start: "7:00 AM",
        end: "9:00 AM",
      },
      {
        id: "s106",
        title: "Client Meetings",
        start: "9:00 AM",
        end: "12:00 PM",
      },
      { id: "s107", title: "Lunch & Break", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s108",
        title: "Follow-ups & Networking",
        start: "1:00 PM",
        end: "3:00 PM",
      },
      {
        id: "s109",
        title: "Report & Planning",
        start: "3:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s110",
        title: "Training & Development",
        start: "4:00 PM",
        end: "5:30 PM",
      },
      { id: "s111", title: "Dinner & Rest", start: "6:30 PM", end: "7:30 PM" },
      {
        id: "s112",
        title: "Relax & Family Time",
        start: "7:30 PM",
        end: "9:00 PM",
      },
      { id: "s113", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "11",
    name: "Student Routine",
    sessions: [
      {
        id: "s114",
        title: "Wake Up & Morning Routine",
        start: "6:30 AM",
        end: "7:00 AM",
      },
      {
        id: "s115",
        title: "Breakfast & Review",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      {
        id: "s116",
        title: "Class / Lectures",
        start: "8:00 AM",
        end: "12:00 PM",
      },
      { id: "s117", title: "Lunch & Break", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s118",
        title: "Homework / Study",
        start: "1:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s119",
        title: "Extracurricular Activities",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      { id: "s120", title: "Dinner", start: "7:00 PM", end: "7:30 PM" },
      {
        id: "s121",
        title: "Relax & Free Time",
        start: "7:30 PM",
        end: "9:00 PM",
      },
      {
        id: "s122",
        title: "Prepare for Sleep",
        start: "9:00 PM",
        end: "9:30 PM",
      },
      { id: "s123", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "12",
    name: "Office Worker Routine",
    sessions: [
      {
        id: "s124",
        title: "Wake Up & Breakfast",
        start: "6:30 AM",
        end: "7:00 AM",
      },
      { id: "s125", title: "Commute", start: "7:00 AM", end: "8:00 AM" },
      { id: "s126", title: "Work Block 1", start: "8:30 AM", end: "12:00 PM" },
      { id: "s127", title: "Lunch Break", start: "12:00 PM", end: "1:00 PM" },
      { id: "s128", title: "Work Block 2", start: "1:00 PM", end: "5:00 PM" },
      { id: "s129", title: "Commute Home", start: "5:00 PM", end: "6:00 PM" },
      { id: "s130", title: "Dinner & Relax", start: "7:00 PM", end: "8:00 PM" },
      {
        id: "s131",
        title: "Family Time / TV",
        start: "8:00 PM",
        end: "9:30 PM",
      },
      {
        id: "s132",
        title: "Sleep Preparation",
        start: "9:30 PM",
        end: "10:00 PM",
      },
      { id: "s133", title: "Sleep", start: "10:30 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "13",
    name: "Healthcare Worker Routine",
    sessions: [
      {
        id: "s134",
        title: "Wake Up & Prepare",
        start: "5:30 AM",
        end: "6:00 AM",
      },
      { id: "s135", title: "Commute", start: "6:00 AM", end: "7:00 AM" },
      { id: "s136", title: "Work Shift", start: "7:00 AM", end: "3:00 PM" },
      { id: "s137", title: "Lunch & Rest", start: "3:00 PM", end: "4:00 PM" },
      {
        id: "s138",
        title: "Exercise / Relax",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      { id: "s139", title: "Dinner", start: "6:00 PM", end: "7:00 PM" },
      {
        id: "s140",
        title: "Family Time / Relax",
        start: "7:00 PM",
        end: "9:00 PM",
      },
      { id: "s141", title: "Sleep", start: "10:00 PM", end: "5:30 AM" },
    ],
  },
  {
    id: "14",
    name: "Writer's Daily Routine",
    sessions: [
      {
        id: "s142",
        title: "Wake Up & Morning Walk",
        start: "6:30 AM",
        end: "7:00 AM",
      },
      {
        id: "s143",
        title: "Breakfast & Journaling",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      {
        id: "s144",
        title: "Writing Session 1",
        start: "8:00 AM",
        end: "11:00 AM",
      },
      { id: "s145", title: "Lunch & Rest", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s146",
        title: "Writing Session 2",
        start: "1:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s147",
        title: "Reading / Research",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      { id: "s148", title: "Dinner & Relax", start: "6:00 PM", end: "7:00 PM" },
      {
        id: "s149",
        title: "Evening Walk / Meditation",
        start: "7:00 PM",
        end: "8:00 PM",
      },
      { id: "s150", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "15",
    name: "Remote Worker Routine",
    sessions: [
      {
        id: "s151",
        title: "Wake Up & Breakfast",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      { id: "s152", title: "Work Block 1", start: "8:00 AM", end: "11:00 AM" },
      { id: "s153", title: "Short Break", start: "11:00 AM", end: "11:15 AM" },
      { id: "s154", title: "Work Block 2", start: "11:15 AM", end: "1:00 PM" },
      { id: "s155", title: "Lunch Break", start: "1:00 PM", end: "2:00 PM" },
      { id: "s156", title: "Work Block 3", start: "2:00 PM", end: "5:00 PM" },
      {
        id: "s157",
        title: "Exercise / Walk",
        start: "5:00 PM",
        end: "6:00 PM",
      },
      { id: "s158", title: "Dinner & Relax", start: "7:00 PM", end: "8:00 PM" },
      {
        id: "s159",
        title: "Leisure / Hobby",
        start: "8:00 PM",
        end: "9:00 PM",
      },
      { id: "s160", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "16",
    name: "Social Media Manager Routine",
    sessions: [
      { id: "s161", title: "Wake Up & Plan", start: "6:30 AM", end: "7:00 AM" },
      {
        id: "s162",
        title: "Content Creation",
        start: "7:00 AM",
        end: "9:00 AM",
      },
      {
        id: "s163",
        title: "Engagement & Replies",
        start: "9:00 AM",
        end: "10:30 AM",
      },
      {
        id: "s164",
        title: "Analytics Review",
        start: "10:30 AM",
        end: "11:30 AM",
      },
      { id: "s165", title: "Lunch & Break", start: "12:00 PM", end: "1:00 PM" },
      {
        id: "s166",
        title: "Strategy Meeting",
        start: "1:00 PM",
        end: "2:00 PM",
      },
      {
        id: "s167",
        title: "Scheduling Posts",
        start: "2:00 PM",
        end: "3:30 PM",
      },
      {
        id: "s168",
        title: "Learning & Research",
        start: "3:30 PM",
        end: "5:00 PM",
      },
      {
        id: "s169",
        title: "Wrap-up & Planning",
        start: "5:00 PM",
        end: "5:30 PM",
      },
      { id: "s170", title: "Dinner & Relax", start: "7:00 PM", end: "8:00 PM" },
      { id: "s171", title: "Sleep", start: "10:00 PM", end: "6:30 AM" },
    ],
  },
  {
    id: "17",
    name: "Executive Routine",
    sessions: [
      {
        id: "s172",
        title: "Wake Up & Meditation",
        start: "5:30 AM",
        end: "6:00 AM",
      },
      { id: "s173", title: "Workout", start: "6:00 AM", end: "7:00 AM" },
      {
        id: "s174",
        title: "Breakfast & News",
        start: "7:00 AM",
        end: "7:30 AM",
      },
      { id: "s175", title: "Office Work", start: "8:00 AM", end: "12:00 PM" },
      {
        id: "s176",
        title: "Lunch & Networking",
        start: "12:00 PM",
        end: "1:00 PM",
      },
      {
        id: "s177",
        title: "Meetings & Calls",
        start: "1:00 PM",
        end: "4:00 PM",
      },
      {
        id: "s178",
        title: "Emails & Wrap-up",
        start: "4:00 PM",
        end: "5:00 PM",
      },
      {
        id: "s179",
        title: "Dinner & Family Time",
        start: "6:30 PM",
        end: "8:00 PM",
      },
      {
        id: "s180",
        title: "Reading & Relax",
        start: "8:00 PM",
        end: "9:30 PM",
      },
      { id: "s181", title: "Sleep", start: "10:00 PM", end: "5:30 AM" },
    ],
  },
  {
    id: "18",
    name: "Student Athlete Routine",
    sessions: [
      {
        id: "s182",
        title: "Wake Up & Breakfast",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      {
        id: "s183",
        title: "Training / Practice",
        start: "7:00 AM",
        end: "9:00 AM",
      },
      { id: "s184", title: "Classes", start: "9:30 AM", end: "12:30 PM" },
      { id: "s185", title: "Lunch & Rest", start: "12:30 PM", end: "1:30 PM" },
      {
        id: "s186",
        title: "Study & Homework",
        start: "1:30 PM",
        end: "3:30 PM",
      },
      {
        id: "s187",
        title: "Physical Therapy / Recovery",
        start: "3:30 PM",
        end: "4:30 PM",
      },
      {
        id: "s188",
        title: "Evening Workout",
        start: "5:00 PM",
        end: "6:00 PM",
      },
      { id: "s189", title: "Dinner", start: "7:00 PM", end: "7:30 PM" },
      {
        id: "s190",
        title: "Relax & Sleep Prep",
        start: "8:00 PM",
        end: "9:30 PM",
      },
      { id: "s191", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "19",
    name: "Night Owl Routine",
    sessions: [
      {
        id: "s192",
        title: "Late Wake Up & Breakfast",
        start: "10:00 AM",
        end: "10:30 AM",
      },
      {
        id: "s193",
        title: "Work / Study Block 1",
        start: "11:00 AM",
        end: "2:00 PM",
      },
      { id: "s194", title: "Lunch Break", start: "2:00 PM", end: "3:00 PM" },
      {
        id: "s195",
        title: "Work / Study Block 2",
        start: "3:00 PM",
        end: "6:00 PM",
      },
      { id: "s196", title: "Dinner", start: "7:00 PM", end: "7:30 PM" },
      {
        id: "s197",
        title: "Evening Leisure",
        start: "7:30 PM",
        end: "10:00 PM",
      },
      {
        id: "s198",
        title: "Deep Work / Projects",
        start: "10:00 PM",
        end: "1:00 AM",
      },
      {
        id: "s199",
        title: "Wind Down & Sleep Prep",
        start: "1:00 AM",
        end: "2:00 AM",
      },
      { id: "s200", title: "Sleep", start: "2:00 AM", end: "10:00 AM" },
    ],
  },
  {
    id: "20",
    name: "Balanced Life Routine",
    sessions: [
      {
        id: "s201",
        title: "Wake Up & Meditation",
        start: "6:00 AM",
        end: "6:30 AM",
      },
      { id: "s202", title: "Exercise", start: "6:30 AM", end: "7:15 AM" },
      { id: "s203", title: "Breakfast", start: "7:15 AM", end: "7:45 AM" },
      { id: "s204", title: "Work / Study", start: "8:00 AM", end: "12:00 PM" },
      { id: "s205", title: "Lunch & Relax", start: "12:00 PM", end: "1:00 PM" },
      { id: "s206", title: "Family Time", start: "1:00 PM", end: "3:00 PM" },
      {
        id: "s207",
        title: "Personal Projects / Hobby",
        start: "3:00 PM",
        end: "5:00 PM",
      },
      { id: "s208", title: "Evening Walk", start: "5:00 PM", end: "6:00 PM" },

      {
        id: "s209",
        title: "Dinner & Social Time",
        start: "6:30 PM",
        end: "8:00 PM",
      },
      { id: "s210", title: "Relax & Read", start: "8:00 PM", end: "9:00 PM" },
      { id: "s211", title: "Sleep", start: "10:00 PM", end: "6:00 AM" },
    ],
  },
  {
    id: "21", // This ID is now unique
    name: "For testing",
    sessions: [
      // New "Check Notification" sessions from 5:45 PM to 6:00 PM, every 1 minute
      // "Check Notification" sessions from 6:00 PM to 6:15 PM
     
 {
  id: "s_test_1234",
  title: "Notification 1",
  start: "12:34 AM",
  end: "12:35 AM",
},
{
  id: "s_test_1235",
  title: "Notification 2",
  start: "12:35 AM",
  end: "12:36 AM",
},
{
  id: "s_test_1236",
  title: "Notification 3",
  start: "12:36 AM",
  end: "12:37 AM",
},
{
  id: "s_test_1237",
  title: "Notification 4",
  start: "12:37 AM",
  end: "12:38 AM",
},
{
  id: "s_test_1238",
  title: "Notification 5",
  start: "12:38 AM",
  end: "12:39 AM",
},
{
  id: "s_test_1239",
  title: "Notification 6",
  start: "12:39 AM",
  end: "12:40 AM",
},
{
  id: "s_test_1240",
  title: "Notification 7",
  start: "12:40 AM",
  end: "12:41 AM",
},
{
  id: "s_test_1241",
  title: "Notification 8",
  start: "12:41 AM",
  end: "12:42 AM",
},
{
  id: "s_test_1242",
  title: "Notification 9",
  start: "12:42 AM",
  end: "12:43 AM",
},
{
  id: "s_test_1243",
  title: "Notification 10",
  start: "12:43 AM",
  end: "12:44 AM",
},
{
  id: "s_test_1244",
  title: "Notification 11",
  start: "12:44 AM",
  end: "12:45 AM",
},
{
  id: "s_test_1245",
  title: "Notification 12",
  start: "12:45 AM",
  end: "12:46 AM",
},
{
  id: "s_test_1246",
  title: "Notification 13",
  start: "12:46 AM",
  end: "12:47 AM",
},
{
  id: "s_test_1247",
  title: "Notification 14",
  start: "12:47 AM",
  end: "12:48 AM",
},
{
  id: "s_test_1248",
  title: "Notification 15",
  start: "12:48 AM",
  end: "12:49 AM",
},
{
  id: "s_test_1249",
  title: "Notification 16",
  start: "12:49 AM",
  end: "12:50 AM",
},
{
  id: "s_test_1250",
  title: "Notification 17",
  start: "12:50 AM",
  end: "12:51 AM",
},


    ],
  },
];
